language: generic
sudo: required
services:
  - docker

before_install:
- docker build -t nowertis/nowern-frontend -f ./WebUI/Dockerfile.dev ./WebUI

#script:
#  - docker run -e CI=true nowertis/nowern-frontend npm run test
