language: generic
sudo: required
services:
  - docker

before_install:
- docker build -t nowertis/nowern-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true nowertis/docker-react npm run test
